TaPP_PZ1_Darhil_Danylo/Controllers/AddClientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class AddClientController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<Client> ClientDAO;

        public AddClientController()
        {
            ClientDAO = DAOFactory.Create<Client>();
        }
        public ActionResult AddClient()
        {
            return View(new Client.Builder().WithLogin("").WithName(""));
        }
        public ActionResult Create(string login, string password, string name, string surname, string patronymic, string phone, string email, string adress)
        {
            if (adress == null)
                adress = " ";
            Client client = new Client.Builder().WithLogin(login).WithPassword(password).WithName(name).WithSurname(surname).WithPatronymic(patronymic).WithPhone(phone).WithEmail(email).WithAdress(adress).Build();
            ClientDAO.Create(client);
            client = null;
            return View("AddClient", client);
        }

    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/AddOrderAutoPartsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.SqlServer.Management.Sdk.Sfc;
using MySqlX.XDevAPI;
using Newtonsoft.Json;
using System.Management;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class AddOrderAutoPartsController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<Order> OrderDAO;
        private readonly IDAO<AutoPart> AutoPartDAO;
        private readonly IDAO<OrdersAutoParts> OrdersAutoPartsDAO;
        public AddOrderAutoPartsController()
        {
            OrderDAO = DAOFactory.Create<Order>();
            AutoPartDAO = DAOFactory.Create<AutoPart>();
            OrdersAutoPartsDAO = DAOFactory.Create<OrdersAutoParts>();
        }
        public ActionResult AddOrderAutoParts()
        {
                List<AutoPart> autoparts = AutoPartDAO.GetAll();
                return View("AddOrderAutoParts", autoparts);
        }
        public ActionResult SearchAutoParts(string searchcriteria)
        {
            List<AutoPart> autoparts = AutoPartDAO.SearchByCriteria(searchcriteria);
            return View("AddOrderAutoParts", autoparts);
        }
        public ActionResult Create(int id, decimal price, int quantity)
        {
            if (TempData.TryGetValue("SerializedOrder", out object serializedOrderObj) && serializedOrderObj is string serializedOrder)
            {
                Order order = JsonConvert.DeserializeObject<Order>(serializedOrder);
                if (order.Status.Id != -1)
                {
                    OrderDAO.Create(order);
                    order.Status.Id = -1;
                }
                OrdersAutoParts ordersAutoParts = new OrdersAutoParts.Builder().WithAutopart(id, quantity, price * quantity/100).WithOrder(0).Build();
                OrdersAutoPartsDAO.Create(ordersAutoParts);
                serializedOrder = JsonConvert.SerializeObject(order);
                TempData["SerializedOrder"] = serializedOrder;
                return RedirectToAction("AddOrderAutoParts", "AddOrderAutoParts");
            }
            return null;
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/AddOrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class AddOrderController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<OrderStatus> OrderStatusDAO;
        private readonly IDAO<Client> ClientDAO;
        private readonly IDAO<Manager> ManagerDAO;
        public AddOrderController()
        {
            OrderStatusDAO = DAOFactory.Create<OrderStatus>();
            ClientDAO = DAOFactory.Create<Client>();
            ManagerDAO = DAOFactory.Create<Manager>();
        }

        public ActionResult AddOrder()
        {
            OrderPropertiesViewModel orderProperties = new OrderPropertiesViewModel();
            orderProperties.Clients = ClientDAO.GetAll();
            orderProperties.Managers = ManagerDAO.GetAll();
            orderProperties.OrderStatuses = OrderStatusDAO.GetAll();
            return View(orderProperties);
        }
        public ActionResult Create(int orderid, int statusid, string createdate, string updatedate, string comment, int clientid, int managerid)
        {
            if (comment == null)
                comment = " ";
            Order order= new Order.Builder().WithId(orderid).WithStatus(statusid).WithCreateDate(Convert.ToDateTime(createdate)).WithUpdateDate(Convert.ToDateTime(updatedate)).WithComment(comment).WithClient(clientid).WithManager(managerid).Build();
            string serializedOrder = JsonConvert.SerializeObject(order);
            TempData["SerializedOrder"] = serializedOrder;
            return RedirectToAction("AddOrderAutoParts", "AddOrderAutoParts");
        }

    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/AddPartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;

namespace CourseProject.Controllers
{
    public class AddPartController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<PartType> PartTypeDAO;
        private readonly IDAO<PartCategory> PartCategoryDAO;
        private readonly IDAO<ManufacturerCountry> ManufacturerCountryDAO;
        private readonly IDAO<ManufacturerBrand> ManufacturerBrandDAO;
        private readonly IDAO<AutoModel> AutoModelDAO;
        private readonly IDAO<AutoPart> AutoPartDAO;
        public AddPartController()
        {
            PartTypeDAO = DAOFactory.Create<PartType>();
            PartCategoryDAO = DAOFactory.Create<PartCategory>();
            ManufacturerCountryDAO = DAOFactory.Create<ManufacturerCountry>();
            ManufacturerBrandDAO = DAOFactory.Create<ManufacturerBrand>();
            AutoModelDAO = DAOFactory.Create<AutoModel>();
            string role = System.IO.File.ReadAllText("UserRole.txt");
            AutoPartDAO = DAOFactory.Create<AutoPart>(role);
        }

        public ActionResult AddPart()
        {
            PartPropertiesViewModel partProperties = new PartPropertiesViewModel();
            partProperties.ManufacturerBrands = ManufacturerBrandDAO.GetAll();
            partProperties.ManufacturerCountries = ManufacturerCountryDAO.GetAll();
            partProperties.AutoModels = AutoModelDAO.GetAll();
            partProperties.PartCategories = PartCategoryDAO.GetAll();
            partProperties.PartTypes = PartTypeDAO.GetAll();
            return View(partProperties);
        }
        public ActionResult Create(string name, string code, string automodel, string parttype,string partcategory,string brand, string country, string description,decimal price,int quantity)
        {
            if (description == null)
                description = " ";
            AutoPart autopart = new AutoPart.Builder().WithName(name).WithCode(code).WithAutomodel(automodel).WithPartType(parttype).WithPartCategory(partcategory).WithManufacturerBrand(brand).WithManufacturerCountry(country).WithDescription(description).WithPrice(price).WithQuantity(quantity).Build();
            AutoPartDAO.Create(autopart);
            PartPropertiesViewModel configpropertie = null;
            return View("AddPart", configpropertie);
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class AuthorizationController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly ClientDAO ClientDAO;
        public AuthorizationController()
        {
            ClientDAO = new ClientDAO();
        }
        public ActionResult BeginAuthorization()
        {
            return View("Authorization",null);
        }
        public ActionResult SetRole(string login, string password)
        {
            string role;
            role=ClientDAO.CheckClient(login,password);
            if (role == null)
                role = "Ви не були авторизовані, не вірний логін або пароль !";
            else 
            {
                System.IO.File.WriteAllText("UserRole.txt", role);
                role = "Ви успішно авторизувались як " + role; 
            }

            return View("Authorization", role);
        }

    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/ManagerClientsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class ManagerClientsController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<Client> ClientDAO;
        public ManagerClientsController()
        {
            ClientDAO = DAOFactory.Create<Client>();
        }
        public ActionResult GetClients()
        {
            List<Client> clients = ClientDAO.GetAll();
            return View("ManagerClients", clients);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            ClientDAO.Delete(id);
            return RedirectToAction(controllerName: "ManagerClients", actionName: "GetClients");
        }
        public ActionResult SearchClients(string searchcriteria)
        {
            List<Client> clients = ClientDAO.SearchByCriteria(searchcriteria);
            return View("ManagerClients", clients);
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/ManagerOrdersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;

namespace CourseProject.Controllers
{
    public class ManagerOrdersController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<OrdersAutoParts> OrdersAutoPartsDAO;
        public ManagerOrdersController()
        {
            OrdersAutoPartsDAO = DAOFactory.Create<OrdersAutoParts>();
        }

        public ActionResult GetOrders()
        {
            List<OrdersAutoParts> ordersAutoParts = OrdersAutoPartsDAO.GetAll();
            return View("ManagerOrders",ordersAutoParts);
        }
        public ActionResult SearchOrders(string searchcriteria)
        {
            List<OrdersAutoParts> ordersAutoParts = OrdersAutoPartsDAO.SearchByCriteria(searchcriteria);
            return View("ManagerOrders", ordersAutoParts);
        }
        public ActionResult Delete(int id)
        {
            OrdersAutoPartsDAO.Delete(id);
            return RedirectToAction(controllerName: "ManagerOrders", actionName: "GetOrders");
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/ManagerPartsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using MySql.Data.MySqlClient;
using System.Diagnostics.Eventing.Reader;
using System.Reflection.PortableExecutable;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;

namespace TPP_PZ1_Darhil_Danylo.Controllers
{
    public class ManagerPartsController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<AutoPart> AutoPartDAO;
        public ManagerPartsController()
        {
            string role = System.IO.File.ReadAllText("UserRole.txt");
            AutoPartDAO = DAOFactory.Create<AutoPart>(role);
        }

        public ActionResult GetAutoParts()
        {
            List<AutoPart> autoparts = AutoPartDAO.GetAll();
            return View("ManagerParts",autoparts);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            AutoPartDAO.Delete(id);
            return RedirectToAction(controllerName: "ManagerParts", actionName: "GetAutoParts");
        }
        public ActionResult SearchAutoParts(string searchcriteria)
        {
            List<AutoPart> autoparts = AutoPartDAO.SearchByCriteria(searchcriteria);
            return View("ManagerParts", autoparts);
        }

    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/UpdateClientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class UpdateClientController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<Client> ClientDAO;
        public UpdateClientController()
        {
            ClientDAO = DAOFactory.Create<Client>();
        }
        public ActionResult UpdateClient(int id)
        {
            Client client = ClientDAO.Get(id);
            return View(client);
        }
        public ActionResult Update(int id, string login, string password, string name, string surname, string patronymic, string phone, string email, string adress)
        {
            if (adress == null)
                adress = " ";
            Client client = new Client.Builder().WithId(id).WithLogin(login).WithPassword(password).WithName(name).WithSurname(surname).WithPatronymic(patronymic).WithPhone(phone).WithEmail(email).WithAdress(adress).Build();
            ClientDAO.Update(client);
            client = null;
            return View("UpdateClient", client);
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Controllers/UpdateOrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPP_PZ_Darhil_Danylo.DAL.DAO.FactoryMethod;
using TPP_PZ_Darhil_Danylo.DAL.ViewModels;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.DAOImp;
using TPP_PZ1_Darhil_Danylo.DAL.DAO.Interfaces;
using TPP_PZ1_Darhil_Danylo.DAL.Models;
using TPP_PZ1_Darhil_Danylo.DAL.ViewModels;

namespace TPP_PZ_Darhil_Danylo.Controllers
{
    public class UpdateOrderController : Controller
    {
        DAOFactory DAOFactory = new DAOFactory();
        private readonly IDAO<Order> OrderDAO;
        private readonly IDAO<OrderStatus> OrderStatusDAO;
        private readonly IDAO<Client> ClientDAO;
        private readonly IDAO<Manager> ManagerDAO;

        public UpdateOrderController()
        {
            OrderDAO = DAOFactory.Create<Order>();
            OrderStatusDAO = DAOFactory.Create<OrderStatus>();
            ClientDAO = DAOFactory.Create<Client>();
            ManagerDAO = DAOFactory.Create<Manager>();

        }
        public ActionResult UpdateOrder(int id)
        {
            OrderPropertiesViewModel orderProperties = new OrderPropertiesViewModel();
            orderProperties.Clients = ClientDAO.GetAll();
            orderProperties.Managers = ManagerDAO.GetAll();
            orderProperties.OrderStatuses = OrderStatusDAO.GetAll();
            orderProperties.Order = OrderDAO.Get(id);
            return View(orderProperties);
        }
        public ActionResult Update(int orderid, int statusid, string createdate, string updatedate, string comment, int clientid, int managerid)
        {
            if (comment == null)
                comment = " ";
            Order order = new Order.Builder().WithId(orderid).WithStatus(statusid).WithCreateDate(Convert.ToDateTime(createdate)).WithUpdateDate(Convert.ToDateTime(updatedate)).WithComment(comment).WithClient(clientid).WithManager(managerid).Build();
              OrderDAO.Update(order);
            OrderPropertiesViewModel orderProperties = null;
            return View("UpdateOrder", orderProperties);
        }
    }
}

TaPP_PZ1_Darhil_Danylo/Views/Shared/AddClient.cshtml
@{
    ViewData["Title"] = "Новий клієнт";
}
<style>
    .tbody {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 60vh;
    }

    .container {
        text-align: center;
    }

    .button-container {
        margin-top: 10px;
    }

    .card-body {
        text-align: left;
    }

    #input-count {
        text-align: center;
    }

</style>

<div class="text-center">
    <h1 class="page-title">Додавання нового клієнта</h1>
</div>
<div class="container mb-3">
    @if (Model == null)
    {
        <div class="tbody ">
            <b style="font-size: 20px;">Новий клієнт був успішно доданий !</b>
        </div>
        <form method="get" action="@Url.Action("AddClient","AddClient")">
            <button type="submit" class="btn btn-info" style="width: 300px;">Додати ще одного клієнта</button>
        </form>
    }
    else
    {
        <form method="post" action="@Url.Action("Create","AddClient")">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="form-group">
                        <label for="login">Логін:</label>
                        <input type="text" id="loginid" name="login" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="password"> Пароль:</label>
                        <input type="text" id="passwordid" name="password" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label for="name">Ім'я:</label>
                        <input type="text" id="nameid" name="name" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="surname">Прізвище:</label>
                        <input type="text" id="surnameid" name="surname" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="patronymic">По-батькові:</label>
                        <input type="text" id="patronymicid" name="patronymic" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="phone">Телефон:</label>
                        <input type="text" id="phoneid" name="phone" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="email">Електронна пошта:</label>
                        <input type="text" id="emailid" name="email" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="adress">Адреса:</label>
                        <input type="text" id="adressid" name="adress" class="form-control" />
                    </div>
                </div>
                <div class="form-group" style="text-align:center; display:flex; justify-content:center; margin-bottom: 10px;">
                    <button type="submit" class="btn btn-primary" style=" width:300px;">Додати клієнта</button>
                </div>
            </div>
        </form>
    }
</div>
<form method="get" style="text-align:center; display:flex; justify-content:center; margin-bottom: 10px;" action="@Url.Action("GetClients","ManagerClients")">
    <button type="submit" class="btn btn-warning" style="width: 300px;">Повернутись до списку клієнтів</button>
</form>

TaPP_PZ1_Darhil_Danylo/Views/Shared/AddOrder.cshtml
@{
    ViewData["Title"] = "Створення замовлення";
}
<style>
    .tbody {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 60vh;
    }

    .container {
        text-align: center;
    }

    .button-container {
        margin-top: 10px;
    }

    .card-body {
        text-align: left;
    }

    #input-count {
        text-align: center;
    }

    .center {
        text-align: center;
    }

    .bold {
        font-weight: bold;
    }
</style>

<div class="text-center">
    <h1 class="page-title">Створення нового замовлення</h1>
</div>
<div class="container mb-3">
    @if (Model == null)
    {
        <div class="tbody">
            <b style="font-size: 20px;">Замовлення було успішно додано!</b>
        </div>
    }
    else
    {
        <form method="post" action="@Url.Action("Create","AddOrder")">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="form-group">
                        <label for="statusid">Статус замовлення:</label>
                        <select id="statusid" name="statusid" class="form-control" required>
                            @foreach (var status in Model.OrderStatuses)
                            {
                                <option value="@status.Id"> @status.Name </option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="createdate">Дата створення замовлення:</label>
                        <input type="text" id="createdateid" name="createdate" class="form-control" value=@DateTime.Now required />
                    </div>
                    <div class="form-group">
                        <label for="updatedate">Дата останнього оновлення замовлення:</label>
                        <input type="text" id="updatedateid" name="updatedate" class="form-control" value=@DateTime.Now required />
                    </div>
                    <div class="form-group">
                        <label for="comment">Коментар:</label>
                        <input type="text" id="commentid" name="comment" class="form-control" value="comment" required />
                    </div>
                    <div class="form-group">
                        <label for="client">Клієнт:</label>
                        <select id="clientid" name="clientid" class="form-control" required>
                            @foreach (var client in Model.Clients)
                            {
                                <option value="@client.Id">@client.Login @client.Name @client.Surname @client.Patronymic </option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="manager">Менеджер:</label>
                        <select id="managerid" name="managerid" class="form-control" required>
                            @foreach (var manager in Model.Managers)
                            {
                                <option value="@manager.Id">@manager.Login @manager.Name @manager.Surname @manager.Patronymic </option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group" style="text-align:center; display:flex; justify-content:center; margin-bottom: 10px;">
                    <button type="submit" class="btn btn-primary" style=" width:300px;">Створити нове замовлення</button>
                </div>
            </div>
        </form>
    }
</div>

<form method="get" style="text-align:center; display:flex; justify-content:center; margin-bottom: 10px;" action="@Url.Action("GetOrders","ManagerOrders")">
    <button type="submit" class="btn btn-warning" style="width: 300px;">Повернутись до замовлень</button>
</form>

TaPP_PZ1_Darhil_Danylo/Views/Shared/AddOrderAutoParts.cshtml
@{
    ViewData["Title"] = "Додайте автозапчастини до замовлення";
}

<style>
    .table, .table-info {
        border-color: black;
    }

    td {
        vertical-align: middle;
        text-align: center;
    }

    th {
        vertical-align: middle;
        text-align: center;
    }

    .inputs {
        text-align: center;
    }
</style>
<div class="text-center">
    <h1 class="page-title">Додайте автозапчастини до замовлення</h1>
</div>
<div class="inputs">
    <form method="get" asp-controller="AddOrderAutoParts" asp-action="SearchAutoParts">
        <label for="searchInput" style="margin-right: 10px;">Пошук:</label>
        <input type="text" id="criteriaid" name="searchcriteria" style="width:70%; margin-right: 10px;" placeholder="Введіть назву або код автозапчастини для пошуку...">
        <button type="submit" class="btn btn-warning" style="margin-bottom: 15px; margin-top: 10px;">Знайти</button>
    </form>
</div>

<div class="text-center">
    <form method="get" style="text-align:center; display:flex; justify-content:center; margin-bottom: 10px;" action="@Url.Action("GetOrders","ManagerOrders")">
        <button type="submit" class="btn btn-warning" style="width: 300px;">Повернутись до замовлень</button>
    </form>

    <table class="table table-hover table-bordered">
        <thead class="table-info">
            <tr>
                <th>№</th>
                <th>Назва автозапчастини</th>
                <th>Код</th>
                <th>Марка автомобіля</th>
                <th>Тип</th>
                <th>Категорія</th>
                <th>Виробник</th>
                <th>Країна виробник</th>
                <th>Ціна</th>
                <th>Кількість</th>
                <th>Обрана кількість</th>
                <th>Додати до кошика</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var autopart in Model)
            {
                <tr>
                    <td>@autopart.Id</td>
                    <td>@autopart.Name</td>
                    <td>@autopart.Code</td>
                    <td>@autopart.AutoModel.AutoModelName</td>
                    <td>@autopart.PartType.TypeName</td>
                    <td>@autopart.PartCategory.CategoryName</td>
                    <td>@autopart.ManufacturerBrand.BrandName</td>
                    <td>@autopart.ManufacturerCountry.CountryName</td>
                    <td>
                        @autopart.Price
                    </td>
                    <td>@autopart.Quantity</td>
                                                <form method="get" action="@Url.Action("Create","AddOrderAutoParts")">

                    <td>
                        <div class="form-group">
                            <input type="number" id="quantity" name="quantity" min="1" value="1" max=@autopart.Quantity class="form-control" required />
                        </div>
                    </td>
                    <td>
                        @if (autopart.Quantity == 0)
                        {
                            <button type="submit" class="add-to-cart-btn disabled" disabled>Змінити</button>
                        }
                        else
                        {
                                <input type="hidden" name="id" value="@autopart.Id" />
                                <input type="hidden" name="price" value="@autopart.Price" />
                                <button type="submit" class="btn btn-info">Додати до замовлення</button>
                        }
                    </td>
                    </form>


                </tr>
            }
        </tbody>
    </table>
</div>



<style>
    .add-to-cart-btn.disabled {
        background-color: indianred;
        cursor: not-allowed;
    }

        .add-to-cart-btn.disabled:hover {
            background-color: #ccc;
        }
</style>